"""Shared helpers for T3 governed audit trail operator tooling."""
from __future__ import annotations

import base64
import hashlib
import ipaddress
import json
import os
import re
import secrets
import socket
import ssl
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path

LOCALHOST_HOSTS = {"127.0.0.1", "localhost", "::1"}
DEFAULT_NS = "cdb"
DEFAULT_DB = "audit_trail"
COMPOSE_ENV_FILENAME = "audit_trail_t3.compose.env"
ENV_FILENAME = "SURREALDB_AUDIT_TRAIL_ENV"
TLS_DIRNAME = "audit_trail_tls"
COMPOSE_FILE = (
    Path(__file__).resolve().parents[2]
    / "infrastructure"
    / "compose"
    / "surrealdb-audit-trail-t3.yml"
)
SCHEMA_FILE = (
    Path(__file__).resolve().parents[2]
    / "infrastructure"
    / "surrealdb"
    / "audit_trail_v0.surql"
)
CONTAINER_NAME = "cdb_surrealdb_audit_trail"
T2_CONTAINER_NAME = "cdb_surrealdb"
REQUIRED_ENV_KEYS = (
    "SURREAL_URL",
    "SURREAL_NS",
    "SURREAL_DB",
    "SURREAL_USER",
    "SURREAL_PASS",
)


@dataclass(frozen=True)
class AuditTrailEnv:
    surreal_url: str
    surreal_ns: str
    surreal_db: str
    surreal_user: str
    surreal_pass: str
    env_file: Path
    tls_dir: Path


def resolve_secrets_path(secrets_path: str | None = None) -> Path:
    if secrets_path:
        return Path(secrets_path)
    return Path(
        os.environ.get(
            "SECRETS_PATH",
            str(Path.home() / "Documents" / ".secrets" / ".cdb"),
        )
    )


def resolve_env_file(secrets_path: str | None = None) -> Path:
    return resolve_secrets_path(secrets_path) / ENV_FILENAME


def load_env_file(env_file: Path) -> AuditTrailEnv:
    if not env_file.is_file():
        raise FileNotFoundError(f"missing env file: {env_file}")

    values: dict[str, str] = {}
    for line in env_file.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip()] = value.strip()

    missing = [key for key in REQUIRED_ENV_KEYS if not values.get(key)]
    if missing:
        raise ValueError(f"env file missing required keys: {', '.join(missing)}")

    return AuditTrailEnv(
        surreal_url=values["SURREAL_URL"].rstrip("/"),
        surreal_ns=values["SURREAL_NS"],
        surreal_db=values["SURREAL_DB"],
        surreal_user=values["SURREAL_USER"],
        surreal_pass=values["SURREAL_PASS"],
        env_file=env_file,
        tls_dir=env_file.parent / TLS_DIRNAME,
    )


def write_env_file(
    env_file: Path,
    *,
    surreal_url: str,
    surreal_user: str,
    surreal_pass: str,
    surreal_ns: str = DEFAULT_NS,
    surreal_db: str = DEFAULT_DB,
) -> None:
    env_file.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "# T3 governed audit trail endpoint — generated by audit_trail_t3_bootstrap.py\n"
        f"SURREAL_URL={surreal_url.rstrip('/')}\n"
        f"SURREAL_NS={surreal_ns}\n"
        f"SURREAL_DB={surreal_db}\n"
        f"SURREAL_USER={surreal_user}\n"
        f"SURREAL_PASS={surreal_pass}\n"
    )
    env_file.write_text(content, encoding="utf-8")


def write_compose_env_file(
    compose_env_file: Path,
    *,
    surreal_user: str,
    surreal_pass: str,
) -> None:
    compose_env_file.parent.mkdir(parents=True, exist_ok=True)
    compose_env_file.write_text(
        f"SURREAL_USER={surreal_user}\nSURREAL_PASS={surreal_pass}\n",
        encoding="utf-8",
    )


def detect_private_lan_ipv4() -> str:
    candidates: list[str] = []

    if sys.platform == "win32":
        try:
            proc = subprocess.run(
                [
                    "powershell",
                    "-NoProfile",
                    "-Command",
                    (
                        "Get-NetIPAddress -AddressFamily IPv4 | "
                        "Where-Object { $_.IPAddress -notlike '127.*' -and "
                        "$_.PrefixOrigin -ne 'WellKnown' } | "
                        "Sort-Object InterfaceMetric | "
                        "Select-Object -ExpandProperty IPAddress"
                    ),
                ],
                capture_output=True,
                text=True,
                check=False,
                timeout=20,
            )
            if proc.returncode == 0:
                candidates.extend(
                    line.strip()
                    for line in proc.stdout.splitlines()
                    if line.strip()
                )
        except (OSError, subprocess.TimeoutExpired):
            pass

    try:
        probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        probe.connect(("8.8.8.8", 80))
        candidates.append(probe.getsockname()[0])
    except OSError:
        pass
    finally:
        try:
            probe.close()
        except Exception:
            pass

    for candidate in candidates:
        try:
            ip = ipaddress.ip_address(candidate)
        except ValueError:
            continue
        if ip.is_loopback or not ip.is_private:
            continue
        return str(ip)

    raise RuntimeError("no private LAN IPv4 detected for non-localhost T3 URL")


def guard_non_localhost(url: str) -> str:
    parsed = urllib.parse.urlparse(url)
    host = (parsed.hostname or "").lower()
    if host in LOCALHOST_HOSTS:
        raise ValueError("T3 endpoint must not use localhost")
    if parsed.scheme not in {"https"}:
        raise ValueError("T3 endpoint must use HTTPS")
    return host


def generate_credentials() -> tuple[str, str]:
    user = f"audit_trail_writer_{secrets.token_hex(4)}"
    password = secrets.token_urlsafe(32)
    return user, password


def _resolve_openssl_executable() -> str:
    candidates = ["openssl"]
    if sys.platform == "win32":
        candidates.extend(
            [
                r"C:\Program Files\Git\usr\bin\openssl.exe",
                r"C:\Program Files (x86)\Git\usr\bin\openssl.exe",
            ]
        )
    for candidate in candidates:
        try:
            proc = subprocess.run(
                [candidate, "version"],
                capture_output=True,
                text=True,
                check=False,
            )
            if proc.returncode == 0:
                return candidate
        except OSError:
            continue
    raise RuntimeError("openssl not found; install OpenSSL or Git for Windows")


def generate_tls_material(tls_dir: Path, *, san_ip: str) -> tuple[Path, Path]:
    tls_dir.mkdir(parents=True, exist_ok=True)
    cert_path = tls_dir / "cert.pem"
    key_path = tls_dir / "key.pem"
    if cert_path.is_file() and key_path.is_file():
        return cert_path, key_path

    openssl = _resolve_openssl_executable()
    cmd = [
        openssl,
        "req",
        "-x509",
        "-newkey",
        "rsa:2048",
        "-keyout",
        str(key_path),
        "-out",
        str(cert_path),
        "-days",
        "365",
        "-nodes",
        "-subj",
        "/CN=cdb-audit-trail-t3",
        "-addext",
        f"subjectAltName=IP:{san_ip},IP:127.0.0.1",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(
            "openssl TLS generation failed; ensure OpenSSL is installed"
        )
    key_path.chmod(0o600)
    return cert_path, key_path


def build_ssl_context(cert_path: Path) -> ssl.SSLContext:
    context = ssl.create_default_context()
    context.load_verify_locations(cafile=str(cert_path))
    context.check_hostname = False
    context.verify_mode = ssl.CERT_REQUIRED
    return context


def endpoint_fingerprint(*, ns: str, db: str, mtls_policy: str = "optional") -> str:
    payload = f"endpoint_class=governed_non_localhost_T3|ns={ns}|db={db}|tls=1|mtls={mtls_policy}"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def health_check(url: str, *, ssl_context: ssl.SSLContext | None = None) -> bool:
    try:
        req = urllib.request.Request(f"{url.rstrip('/')}/health", method="GET")
        with urllib.request.urlopen(req, timeout=5, context=ssl_context) as resp:
            return resp.status == 200
    except Exception:
        return False


def sql_request(
    env: AuditTrailEnv,
    sql: str,
    *,
    ssl_context: ssl.SSLContext | None = None,
    ns: str | None = None,
    db: str | None = None,
) -> tuple[int, bytes]:
    token = base64.b64encode(
        f"{env.surreal_user}:{env.surreal_pass}".encode()
    ).decode()
    headers = {
        "Accept": "application/json",
        "Content-Type": "text/plain",
        "Authorization": f"Basic {token}",
        "surreal-ns": ns or env.surreal_ns,
        "surreal-db": db or env.surreal_db,
    }
    req = urllib.request.Request(
        f"{env.surreal_url}/sql",
        data=sql.encode("utf-8"),
        headers=headers,
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30, context=ssl_context) as resp:
            return resp.status, resp.read()
    except urllib.error.HTTPError as exc:
        return exc.code, exc.read()


def check_statement_results(body: bytes) -> list[dict]:
    raw = body.decode("utf-8", errors="replace")
    if not raw.strip():
        raise ValueError("empty /sql response body")
    results = json.loads(raw)
    if not isinstance(results, list):
        raise ValueError("expected JSON array from /sql")
    for idx, item in enumerate(results):
        if not isinstance(item, dict):
            raise ValueError(f"statement {idx}: expected object")
        if item.get("status") != "OK":
            detail = item.get("detail") or item.get("result") or item
            raise ValueError(f"statement {idx} failed: {detail!s}"[:300])
    return results


def container_network_names(container_name: str) -> tuple[bool, set[str]]:
    proc = subprocess.run(
        [
            "docker",
            "inspect",
            container_name,
            "--format",
            "{{range $k, $v := .NetworkSettings.Networks}}{{$k}} {{end}}",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        return False, set()
    return True, {part for part in proc.stdout.strip().split() if part}


def redact_output(text: str, env: AuditTrailEnv) -> str:
    redacted = text
    for secret in (
        env.surreal_pass,
        env.surreal_user,
        env.surreal_url,
        urllib.parse.urlparse(env.surreal_url).hostname or "",
    ):
        if secret:
            redacted = redacted.replace(secret, "[REDACTED]")
    redacted = re.sub(r"https?://[^\s\"']+", "[REDACTED_URL]", redacted)
    redacted = re.sub(
        r"\b(?:\d{1,3}\.){3}\d{1,3}\b", "[REDACTED_IP]", redacted
    )
    return redacted
